[http.middlewares.simpleAuth.basicAuth]
  users = [
    "admin:$apr1$hR1niB3v$rrLbUoAuySzeBye3cRHYB." # admin:admin
  ]

[http.routers.api]
  rule = "Host(`traefik.domain.test`)"
  entrypoints = ["websecure"]
  middlewares = ["simpleAuth"]
  service = "api@internal"
  [http.routers.api.tls]
    certResolver = "lets-encrypt"