version: '3'

networks:
  internal:
    external: false

services:

  postgres:
    image: postgres:10
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=your_secure_password
      - POSTGRES_USER=postgres
    volumes:
      - ./data:/var/lib/postgresql/data
    ports: 
      - "5432:5432"
    networks:
      - internal
    labels:
      - traefik.enable=false