version: '3'

networks:
  web:
    external: true
  internal:
    external: false

services:
  mysql:
    image: 'mysql:5.7'
    container_name: mysql
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: your_secure_password
    volumes:
      - './data:/var/lib/mysql'
    networks:
      - internal
    labels:
      - traefik.enable=false

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    links:
      - 'mysql:mysql'
    labels:
      - traefik.http.routers.phpmyadmin.rule=Host(`phpmyadmin.example.com`)
      - traefik.http.routers.phpmyadmin.tls=true
      - traefik.http.routers.phpmyadmin.tls.certresolver=lets-encrypt
      - traefik.port=80
    networks:
      - internal
      - web
