version: "3"

networks:
  web:
    external: true

services:
  whoami:
    image: "traefik/whoami"
    container_name: whoami
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.yourdomain.local`)"
      - "traefik.http.routers.whoami.entrypoints=web"
      - "traefik.port=80"
    networks:
      - web