version: "3"

networks:
  web:
    external: true
  internal:
    external: false

services:
  whoami:
    image: "traefik/whoami"
    labels:
      - traefik.enable=true
      - traefik.http.routers.whoami.rule=Host(`whoami.domain.test`)
      - traefik.http.routers.whoami.entrypoints=web
      - traefik.port=80
    networks:
      - internal
      - web

  blog:
    image: wordpress:5.5
    environment:
      WORDPRESS_DB_PASSWORD: your_secure_password
    labels:
      - traefik.http.routers.blog.rule=Host(`blog.domain.test`)
      - traefik.http.routers.blog.tls=true
      - traefik.http.routers.blog.tls.certresolver=lets-encrypt
      - traefik.port=80
    networks:
      - internal
      - web
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: your_secure_password
    networks:
      - internal
    labels:
      - traefik.enable=false

  adminer:
    image: adminer:4.6.3-standalone
    labels:
    labels:
      - traefik.http.routers.adminer.rule=Host(`adminer.domain.test`)
      - traefik.http.routers.adminer.tls=true
      - traefik.http.routers.adminer.tls.certresolver=lets-encrypt
      - traefik.port=8080
    networks:
      - internal
      - web
    depends_on:
      - mysql