version: "3.3"

networks:
  web:
    external: true
  internal:
    external: false

services:

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.phpmyadmin.rule=Host(`phpmyadmin.yourdomain.com`)"
      - "traefik.http.routers.phpmyadmin.tls=true"
      - "traefik.http.routers.phpmyadmin.tls.certresolver=lets-encrypt"
      - "traefik.port=80"
    networks:
      - internal
      - web
