version: "3"

networks:
  web:
    external: true
  internal:
    external: false

services:

  adminer:
    image: adminer:4.7.7
    labels:
      - traefik.http.routers.adminer.rule=Host(`adminer.domain.test`)
      - traefik.http.routers.adminer.tls=true
      - traefik.http.routers.adminer.tls.certresolver=lets-encrypt
      - traefik.port=8080
    networks:
      - internal
      - web
    depends_on:
      - mysql
      - postgres