version: '3'

networks:
  web:
    external: true
  internal:
    external: false

services:

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    volumes:
      - ./data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - traefik.http.routers.portainer.rule=Host(`portainer.domain.test`)
      - traefik.http.routers.portainer.tls=true
      - traefik.http.routers.portainer.tls.certresolver=lets-encrypt
      - traefik.port=8000
    ports:
      - "8000:8000"
      - "9443:9443"
    networks:
      - internal
      - web