version: "3.3"

networks:
  internal:
    external: false

services:

  mysql:
    image: 'mysql:5.7'
    container_name: mysql
    restart: always
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=your_secure_password
    volumes:
      - './data:/var/lib/mysql'
    networks:
      - internal
    labels:
      - "traefik.enable=false"
