version: '2'

services:

  portainer.app:
    image: portainer/portainer
    container_name: portainer.app
    volumes:
      - ./data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
        VIRTUAL_HOST: your-website-one.tld
        VIRTUAL_PORT: 9000
        LETSENCRYPT_HOST: your-website-one.tld
        LETSENCRYPT_EMAIL: email@example.com
    expose:
      - "9000"
    ports:
      - "9000:9000"

networks:
 default:
  external:
   name: nginx-proxy